//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical1_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public long id { get; set; }
        public string name { get; set; }
        public string section { get; set; }
        public double grade1 { get; set; }
        public double rating { get; set; }
        public string remarks { get; set; }
    }
}
