//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical1_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class stud_sched
    {
        public long idSched { get; set; }
        public string stud_id { get; set; }
        public long idSubj { get; set; }
    }
}
