//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical1_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public long idSubj { get; set; }
        public string subject1 { get; set; }
        public string time { get; set; }
        public string day { get; set; }
        public string instructor { get; set; }
        public string room { get; set; }
        public string subj_id { get; set; }
    }
}
